### PR TITLE
ASAN Bug Fixes (use-after-free)

### LINKED ISSUE #61: ASAN error (use-after-free)
See the error caught by:
https://github.com/microsoft/jrt-controller/actions/runs/15440458534/job/43456789613?pr=60

agent/jrtc_agent_test

Image

```
2025-06-04T12:20:15.491526Z [JBPF][MEM_MGMT][DEBUG]: Successfully created memory arena of size 1073741824 at address 0x7f2994cf6000
2025-06-04T12:20:15.492048Z [JBPF][IO][DEBUG]: Primary initialization successful
[INFO:/jrtc/src/router/jrtc_router.c:jrtc_router_init:331] [INFO]: IO initilized successfully
[INFO:/jrtc/jrtc_tests/agent/jrtc_agent_test.c:start_router:55] [INFO]: Router initialized successfully
[INFO:/jrtc/jrtc_tests/agent/jrtc_agent_test.c:main:85] [INFO]: Starting test for agent API...
[INFO:/jrtc/jrtc_tests/agent/jrtc_agent_test.c:test_agent_api:66] [INFO]: Initializing agent_init()...
2025-06-04T12:20:15.492465Z [JBPF][IO][INFO]: Directory '/tmp/jbpf' already exists.
=================================================================
==10468==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f2a17208440 at pc 0x5578c0336f7a bp 0x7f2994cf4d40 sp 0x7f2994cf4d30
READ of size 1 at 0x7f2a17208440 thread T2
2025-06-04T12:20:15.500092Z [JBPF][IO][ERROR]: Cannot register a primary process
2025-06-04T12:20:15.500416Z [JBPF][IO][INFO]: Received new incoming connection from control channel
2025-06-04T12:20:15.500470Z [JBPF][IO][INFO]: Process connected. Initiating registration
2025-06-04T12:20:15.501211Z [JBPF][IO][DEBUG]: Sent 1048608 bytes
2025-06-04T12:20:15.501255Z [JBPF][IO][DEBUG]: Received 1048608 bytes
2025-06-04T12:20:15.510734Z [JBPF][IO][INFO]: Sent registration request 1048608 bytes
2025-06-04T12:20:15.513801Z [JBPF][IO][INFO]: Registered new peer with socket fd 8
2025-06-04T12:20:15.514445Z [JBPF][MEM_MGMT][INFO]: Trying 1GB persistent huge pages (1073741824 bytes)
2025-06-04T12:20:15.514478Z [JBPF][MEM_MGMT][INFO]: No huge page allocation
2025-06-04T12:20:15.514494Z [JBPF][MEM_MGMT][INFO]: Openning shared memory with name jbpf_io_8
2025-06-04T12:20:15.515133Z [JBPF][MEM_MGMT][INFO]: Directory '/tmp/jbpf' already exists.
2025-06-04T12:20:15.516540Z [JBPF][MEM_MGMT][INFO]: Memory allocated successfully at address 0x7f2952c43000
2025-06-04T12:20:15.516641Z [JBPF][MEM_MGMT][INFO]: Allocated pages mlocked in memory
    #0 0x5578c0336f79 in jrtc_router_thread_start /jrtc/src/router/jrtc_router.c:273
    #1 0x7f2a1957da41 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #2 0x7f2a1913eaa3  (/lib/x86_64-linux-gnu/libc.so.6+0x9caa3) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #3 0x7f2a191cbc3b  (/lib/x86_64-linux-gnu/libc.so.6+0x129c3b) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)

Address 0x7f2a17208440 is located in stack of thread T0 at offset 64 in frame
    #0 0x5578c0333d38 in start_router /jrtc/jrtc_tests/agent/jrtc_agent_test.c:35

  This frame has 1 object(s):
    [48, 288) 'config' (line 36) <== Memory access at offset 64 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-return /jrtc/src/router/jrtc_router.c:273 in jrtc_router_thread_start
Shadow bytes around the buggy address:
  0x7f2a17208180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f2a17208200: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a17208280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a17208300: f5 f5 f5 f5 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f2a17208380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7f2a17208400: f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5
  0x7f2a17208480: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a17208500: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x7f2a17208580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f2a17208600: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a17208680: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T2 created by T0 here:
    #0 0x7f2a196141f9 in pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x5578c0336205 in jrtc_router_init /jrtc/src/router/jrtc_router.c:381

==10468==ABORTING
```

### PR DESCRIPTION
**Pull request by doctorlai-msrc**
This PR avoids passing around a stack-allocated config object that may become invalid once the function exits. This was causing intermittent segmentation faults, as reported by ASAN. The fix involves ensuring that the config object is properly heap-allocated or safely scoped to avoid dangling references.

This PR closes #61

### CODE REVIEW

File: src/controller/jrtc_int.c [hunk 1]
```diff
@@ -427,27 +427,34 @@ start_jrtc(const char* config_file)
 
     sem_init(&jrtc_stop, 0, 0);
 
-    jrtc_config_t jrtc_config = {0};
-    res = set_config_values(config_file, &jrtc_config);
+    jrtc_config_t* jrtc_config = malloc(sizeof(jrtc_config_t));
```
Comment (xfoukas) [inline src/controller/jrtc_int.c:430]: No need to use heap-based allocation here. We just need to call `jrtc_router_stop()` at the appropriate place.

File: jrtc_tests/agent/jrtc_agent_test.c [hunk 2]
```diff
@@ -80,10 +79,17 @@ test_agent_api()
...
+    if (!config) {
+        fprintf(stderr, "Failed to allocate memory for jrtc_config.\n");
+        return -1;
+    }
     jrtc_logger(JRTC_INFO, "Starting the router...\n");
-    assert(start_router() == 0);
+    assert(start_router(config) == 0);
     jrtc_logger(JRTC_INFO, "Starting test for agent API...\n");
     assert(test_agent_api() == 0);
     jrtc_logger(JRTC_INFO, "Test completed.\n");
```
Comment (xfoukas) [inline jrtc_tests/agent/jrtc_agent_test.c:92]: Must call `jrtc_router_stop()`

**Review by xfoukas — CHANGES_REQUESTED** [review]

**Review by xfoukas — APPROVED** [review]
